services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    restart: always
    ports:
      - "8181:8000"
    command: start --user root --pass root file:/data/srdb.db
    volumes:
      - surrealdb-data:/data
    networks:
      - proxy

volumes:
  surrealdb-data:

networks:
  proxy:
    external: true
