services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - mailpit-data:/data
    networks:
      - proxy

volumes:
  mailpit-data:

networks:
  proxy:
    external: true
