#!/bin/bash
# ============================================================
# ESSENTIALS
# The stuff you need to remember as a server admin
# Not a reference — these are the commands that matter daily
# ============================================================

clear
echo ""
echo "  =================================================="
echo "  ESSENTIALS — The Only Commands You Need"
echo "  =================================================="

echo ""
echo "  DAILY LIFE"
echo "  ─────────────────────────────────────"
echo "  ls                     what's here"
echo "  cd /path               go somewhere"
echo "  cd ..                  go back"
echo "  cd ~                   go home"
echo "  nano file              edit a file"
echo "  cat file               read a file"
echo "  Ctrl+C                 stop whatever is running"
echo "  Tab                    auto-complete (USE THIS)"
echo "  Up arrow               previous command"
echo "  history | grep word    find a command you ran before"

echo ""
echo "  DOCKER — ALL YOU NEED"
echo "  ─────────────────────────────────────"
echo "  dps                    what's running"
echo "  docker logs -f NAME    see what a container is doing"
echo "  docker restart NAME    kick it"
echo "  cd /srv/docker/NAME    go to a project"
echo "  docker compose up -d   start it"
echo "  docker compose down    stop it"
echo "  docker compose pull    update it"
echo "  docker compose up -d   start the updated version"

echo ""
echo "  WHEN SOMETHING IS WRONG"
echo "  ─────────────────────────────────────"
echo "  health                 is everything running?"
echo "  ports                  what's on what port?"
echo "  docker logs -f NAME    what is the container saying?"
echo "  sudo reboot            turn it off and on again"
echo "  free -h                out of memory?"
echo "  df -h                  out of disk?"

echo ""
echo "  SECURITY — KNOW THIS"
echo "  ─────────────────────────────────────"
echo "  sec                    am I under attack?"
echo "  sudo ufw status        is my firewall on?"
echo "  sudo fail2ban-client status sshd"
echo "                         who got banned?"
echo "  Don't run random commands from the internet"
echo "  Don't install random .sh scripts from strangers"
echo "  If something feels wrong, run 'sec' first"

echo ""
echo "  KEEPING IT ALIVE"
echo "  ─────────────────────────────────────"
echo "  server-backup          backup now"
echo "  kit-update             update the kit"
echo "  sudo apt update && sudo apt upgrade -y"
echo "                         update the OS"
echo "  docker system prune -a clean up disk space"

echo ""
echo "  YOUR SERVER KIT"
echo "  ─────────────────────────────────────"
echo "  menu                   command center"
echo "  health                 service status"
echo "  sec                    security status"
echo "  hw                     hardware status"
echo "  ports                  port scan"
echo "  howdo                  search for answers"
echo "  cheat                  full cheat sheet"
echo "  whats-next             guided checklist"
echo "  dash                   tmux dashboard"
echo "  deploy                 deploy from GitHub"

echo ""
echo "  THE GOLDEN RULES"
echo "  ─────────────────────────────────────"
echo "  1. If you don't know what it does, don't run it"
echo "  2. 'sudo' means you're running as GOD — be careful"
echo "  3. 'rm -rf' deletes forever — no recycle bin"
echo "  4. Tab key is your best friend — auto-completes everything"
echo "  5. Up arrow shows your last command"
echo "  6. Ctrl+C stops anything"
echo "  7. When in doubt: health, sec, ports"
echo "  8. If it's really broken: sudo reboot"
echo ""
echo "  =================================================="
echo ""
