#!/usr/bin/env bash
# new-service — add any Docker service to the server with correct port, folder, and naming
# Usage:
#   new-service add <category> <name> [project-prefix]
#   new-service list                    # show all running services + ports
#   new-service ports                   # show claimed vs available ports by lane
#   new-service check <port>            # is this port free?
#
# Categories: infrastructure, monitoring, automation, database, api, notifications, storage, admin, ai
#
# Examples:
#   new-service add database redis              → /srv/docker/redis/ port 6379
#   new-service add database redis keyknox      → /srv/docker/keyknox-redis/ port 6380
#   new-service add automation n8n              → /srv/docker/n8n/ port 5678
#   new-service add notifications ntfy          → /srv/docker/ntfy/ port 8085

set -euo pipefail

DOCKER_ROOT="${DOCKER_ROOT:-/srv/docker}"
HUB_PORT=8765

# ── Color helpers ──────────────────────────────────────────────────────────────
BLU='\033[0;34m'; GRN='\033[0;32m'; YLW='\033[0;33m'; RED='\033[0;31m'; NC='\033[0m'; BOLD='\033[1m'
info()    { echo -e "${BLU}→${NC} $1"; }
success() { echo -e "${GRN}✓${NC} $1"; }
warn()    { echo -e "${YLW}⚠${NC}  $1"; }
fail()    { echo -e "${RED}✗${NC} $1"; exit 1; }

# ── Port lane definitions ──────────────────────────────────────────────────────
# Format: "START END RESERVED_CSV"
declare -A LANE_RANGES=(
  [infrastructure]="3000 3099 3000"
  [monitoring]="19000 19999 19999"
  [automation]="5600 5699 5678"
  [database]="6300 6399 6379"
  [api]="8000 8099 8082,8085,8090"
  [notifications]="8080 8089 8085"
  [storage]="9000 9099 9000,9001"
  [admin]="9400 9499 9443"
  [ai]="11000 11999 11434"
)

# Known taken ports (globally reserved)
GLOBALLY_RESERVED="80,81,443,8765,22"

# ── Find next free port in a lane ─────────────────────────────────────────────
find_next_port() {
  local lane="$1"
  local preferred="${2:-}"

  if [[ -z "${LANE_RANGES[$lane]:-}" ]]; then
    fail "Unknown category: $lane. Valid: ${!LANE_RANGES[*]}"
  fi

  read -r start end _ <<< "${LANE_RANGES[$lane]}"

  # If a preferred port given, try it first
  if [[ -n "$preferred" ]]; then
    if ! ss -tlnp | grep -q ":${preferred} "; then
      echo "$preferred"
      return
    fi
    warn "Port $preferred is in use, finding next free port in lane..."
  fi

  for port in $(seq "$start" "$end"); do
    # Skip globally reserved
    if echo "$GLOBALLY_RESERVED" | grep -qw "$port"; then continue; fi
    # Skip if already listening
    if ss -tlnp 2>/dev/null | grep -q ":${port} "; then continue; fi
    echo "$port"
    return
  done

  fail "No free ports in $lane lane ($start-$end). Check what's running."
}

# ── Generate a minimal compose file ───────────────────────────────────────────
generate_compose() {
  local name="$1"
  local port="$2"
  local image="${3:-}"

  cat <<COMPOSE
# =============================================================================
# ${name^^} — Auto-generated by new-service
# Port: ${port} (host) → container internal port
# Data: ${name}-data volume
# Manage: cd ${DOCKER_ROOT}/${name} && docker compose [up -d | down | logs -f]
# =============================================================================

services:
  ${name}:
    image: ${image:-REPLACE_WITH_IMAGE}
    container_name: ${name}
    restart: always
    ports:
      - "${port}:REPLACE_WITH_INTERNAL_PORT"
    volumes:
      - ${name}-data:/data
    networks:
      - proxy

volumes:
  ${name}-data:

networks:
  proxy:
    external: true
COMPOSE
}

# ── Check if proxy network exists ─────────────────────────────────────────────
ensure_proxy_network() {
  if ! docker network ls --format '{{.Name}}' 2>/dev/null | grep -q "^proxy$"; then
    warn "proxy network not found — NPM must be running first"
    warn "Run: cd ${DOCKER_ROOT}/npm && docker compose up -d"
    exit 1
  fi
}

# ── port-scan output ──────────────────────────────────────────────────────────
cmd_ports() {
  echo ""
  echo -e "${BOLD}  Port Status — All Lanes${NC}"
  echo "  ────────────────────────────────────────────────────"

  # Running containers
  echo ""
  echo -e "  ${BOLD}Running containers:${NC}"
  docker ps --format '  {{.Names}}\t{{.Ports}}' 2>/dev/null | \
    awk -F'\t' '{printf "  %-20s %s\n", $1, $2}' || echo "  (docker not running)"

  echo ""
  echo -e "  ${BOLD}All bound ports:${NC}"
  ss -tlnp 2>/dev/null | awk '/LISTEN/{
    split($4, a, ":")
    port = a[length(a)]
    split($6, b, "\"")
    proc = b[2]
    if (port+0 > 0) printf "  %-6s %s\n", port, proc
  }' | sort -n

  echo ""
  echo -e "  ${BOLD}Lane availability:${NC}"
  for lane in infrastructure monitoring automation database api notifications storage admin ai; do
    read -r start end _ <<< "${LANE_RANGES[$lane]}"
    used=$(ss -tlnp 2>/dev/null | awk -v s="$start" -v e="$end" '/LISTEN/{
      split($4,a,":"); p=a[length(a)]+0; if(p>=s && p<=e) count++
    } END {print count+0}')
    echo -e "  ${BLU}${lane}${NC} (${start}-${end}): ${used} ports in use"
  done
  echo ""
}

# ── check single port ─────────────────────────────────────────────────────────
cmd_check() {
  local port="${1:-}"
  [[ -z "$port" ]] && fail "Usage: new-service check <port>"

  if ss -tlnp 2>/dev/null | grep -q ":${port} "; then
    proc=$(ss -tlnp 2>/dev/null | awk -v p=":${port} " '$0~p{split($6,a,"\""); print a[2]}')
    echo -e "${RED}✗${NC} Port ${port} is IN USE by: ${proc:-unknown}"
  else
    echo -e "${GRN}✓${NC} Port ${port} is FREE"
  fi
}

# ── list services ─────────────────────────────────────────────────────────────
cmd_list() {
  echo ""
  echo -e "${BOLD}  Running Services${NC}"
  echo "  ────────────────────────────────────────────────────"
  docker ps --format '  {{.Names}}\t{{.Status}}\t{{.Ports}}' 2>/dev/null | \
    column -t -s $'\t' || echo "  (no containers running)"

  echo ""
  echo -e "${BOLD}  ${DOCKER_ROOT} directories:${NC}"
  ls "${DOCKER_ROOT}/" 2>/dev/null | sed 's/^/  /' || echo "  (empty)"
  echo ""
}

# ── add a service ─────────────────────────────────────────────────────────────
cmd_add() {
  local category="${1:-}"
  local name="${2:-}"
  local prefix="${3:-}"

  [[ -z "$category" || -z "$name" ]] && {
    echo "Usage: new-service add <category> <name> [project-prefix]"
    echo "Categories: ${!LANE_RANGES[*]}"
    exit 1
  }

  # Build full service name
  local full_name
  if [[ -n "$prefix" ]]; then
    full_name="${prefix}-${name}"
  else
    full_name="$name"
  fi

  local service_dir="${DOCKER_ROOT}/${full_name}"
  local compose_file="${service_dir}/docker-compose.yml"

  # Check if already exists
  if [[ -d "$service_dir" ]]; then
    warn "Directory $service_dir already exists"
    if [[ -f "$compose_file" ]]; then
      warn "Compose file exists — starting existing service"
      cd "$service_dir" && docker compose up -d
      success "$full_name started"
      exit 0
    fi
  fi

  ensure_proxy_network

  # Find port
  local port
  port=$(find_next_port "$category")

  echo ""
  echo -e "${BOLD}  Adding service: ${full_name}${NC}"
  echo -e "  Category: ${category}"
  echo -e "  Port:     ${port}"
  echo -e "  Path:     ${service_dir}"
  echo ""

  # Create directory
  sudo mkdir -p "$service_dir"

  # Generate compose file
  generate_compose "$full_name" "$port" | sudo tee "$compose_file" > /dev/null

  # Open UFW
  if command -v ufw >/dev/null 2>&1; then
    sudo ufw allow "${port}/tcp" comment "new-service: ${full_name}" >/dev/null 2>&1 && \
      success "UFW: port ${port} opened"
  fi

  echo ""
  warn "Compose file created at: ${compose_file}"
  warn "You need to set the correct image and internal port before starting."
  echo ""
  echo -e "  Edit: ${YLW}sudo nano ${compose_file}${NC}"
  echo -e "  Then: ${GRN}cd ${service_dir} && docker compose up -d${NC}"
  echo ""
  echo -e "  Once running, hub discovers it automatically on next refresh."
  success "Service scaffold created: ${full_name} → port ${port}"
  # --- Offer to add to server.manifest.yml ---
  _MANIFEST_PATH=""
  for _cand in ~/server-kit/server.manifest.yml /srv/server-kit/server.manifest.yml /opt/server-kit/server.manifest.yml; do
    _cand="${_cand/#\~/$HOME}"
    if [[ -f "$_cand" ]]; then _MANIFEST_PATH="$_cand"; break; fi
  done
  if [[ -n "$_MANIFEST_PATH" ]]; then
    echo ""
    read -rp "  Add ${full_name} to server.manifest.yml? (y/n): " _add_mf
    if [[ "${_add_mf:-n}" == "y" ]]; then
      printf '\n  - name: %s\n    port: %s\n    category: %s\n    type: docker\n    compose: %s\n    required: false\n' \
        "$full_name" "$port" "$category" "$service_dir" >> "$_MANIFEST_PATH"
      success "Added ${full_name} to server.manifest.yml"
    fi
  fi
}

# ── Main ──────────────────────────────────────────────────────────────────────
CMD="${1:-}"
shift || true

case "$CMD" in
  add)    cmd_add "$@" ;;
  list)   cmd_list ;;
  ports)  cmd_ports ;;
  check)  cmd_check "$@" ;;
  help|"")
    echo ""
    echo -e "${BOLD}  new-service — Service scaffolding tool${NC}"
    echo ""
    echo "  Commands:"
    echo "    new-service add <category> <name> [prefix]   Add a new service"
    echo "    new-service list                              List running services"
    echo "    new-service ports                             Show port usage by lane"
    echo "    new-service check <port>                      Check if a port is free"
    echo ""
    echo "  Categories: ${!LANE_RANGES[*]}"
    echo ""
    echo "  Examples:"
    echo "    new-service add database redis"
    echo "    new-service add database redis keyknox        # isolated for keyknox project"
    echo "    new-service add notifications ntfy"
    echo "    new-service add automation n8n"
    echo ""
    ;;
  *)
    fail "Unknown command: $CMD. Run 'new-service help'"
    ;;
esac
